-- CREATE TABLE FOR CSV IMPORT
CREATE TABLE episodes (
	EPISODE VARCHAR,
	TITLE VARCHAR,
	APPLE_FRAME VARCHAR,
	AURORA_BOREALIS VARCHAR,
	BARN VARCHAR,
	BEACH VARCHAR,
	BOAT VARCHAR,
	BRIDGE VARCHAR,
	BUILDING VARCHAR,
	BUSHES VARCHAR,
	CABIN VARCHAR,
	CACTUS VARCHAR,
	CIRCLE_FRAME VARCHAR,
	CIRRUS VARCHAR,
	CLIFF VARCHAR,
	CLOUDS VARCHAR,
	CONIFER VARCHAR,
	CUMULUS VARCHAR,
	DECIDUOUS VARCHAR,
	DIANE_ANDRE VARCHAR,
	DOCK VARCHAR,
	DOUBLE_OVAL_FRAME VARCHAR,
	FARM VARCHAR,
	FENCE VARCHAR,
	FIRE VARCHAR,
	FLORIDA_FRAME VARCHAR,
	FLOWERS VARCHAR,
	FOG VARCHAR,
	FRAMED VARCHAR,
	GRASS VARCHAR,
	GUEST VARCHAR,
	HALF_CIRCLE_FRAME VARCHAR,
	HALF_OVAL_FRAME VARCHAR,
	HILLS VARCHAR,
	LAKE VARCHAR,
	LAKES VARCHAR,
	LIGHTHOUSE VARCHAR,
	MILL VARCHAR,
	MOON VARCHAR,
	MOUNTAIN VARCHAR,
	MOUNTAINS VARCHAR,
	NIGHT VARCHAR,
	OCEAN VARCHAR,
	OVAL_FRAME VARCHAR,
	PALM_TREES VARCHAR,
	PATH VARCHAR,
	PERSON VARCHAR,
	PORTRAIT VARCHAR,
	RECTANGLE_3D_FRAME VARCHAR,
	RECTANGULAR_FRAME VARCHAR,
	RIVER VARCHAR,
	ROCKS VARCHAR,
	SEASHELL_FRAME VARCHAR,
	SNOW VARCHAR,
	SNOWY_MOUNTAIN VARCHAR,
	SPLIT_FRAME VARCHAR,
	STEVE_ROSS VARCHAR,
	STRUCTURE VARCHAR,
	SUN VARCHAR,
	TOMB_FRAME VARCHAR,
	TREE VARCHAR,
	TREES VARCHAR,
	TRIPLE_FRAME VARCHAR,
	WATERFALL VARCHAR,
	WAVES VARCHAR,
	WINDMILL VARCHAR,
	WINDOW_FRAME VARCHAR,
	WINTER VARCHAR,
	WOOD_FRAMED VARCHAR
)

-- IMPORTED CSV FILE (MUST CHANGE ESCAPE PRIOR TO IMPORT (EX: INSTEAD OF ' USE /))
-- NOTE: COULD NOT IMPORT WITH INT DATA TYPE FOR RELEVANT COLUMNS (MUST USE VARCHAR).

-- REMOVE HEADER ROW SO DATA TYPE CAN BE ALTERED.
DELETE FROM episodes WHERE APPLE_FRAME LIKE 'APPLE_FRAME'

-- ALTER DATA TYPE ACCROSS COLUMNS FROM VARCHAR TO INT.
ALTER TABLE episodes ALTER COLUMN
APPLE_FRAME TYPE integer USING APPLE_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
AURORA_BOREALIS TYPE integer USING AURORA_BOREALIS::integer;

ALTER TABLE episodes ALTER COLUMN
BARN TYPE integer USING BARN::integer;

ALTER TABLE episodes ALTER COLUMN
BEACH TYPE integer USING BEACH::integer;

ALTER TABLE episodes ALTER COLUMN
BOAT TYPE integer USING BOAT::integer;

ALTER TABLE episodes ALTER COLUMN
BRIDGE TYPE integer USING BRIDGE::integer;

ALTER TABLE episodes ALTER COLUMN
BUILDING TYPE integer USING BUILDING::integer;

ALTER TABLE episodes ALTER COLUMN
BUSHES TYPE integer USING BUSHES::integer;

ALTER TABLE episodes ALTER COLUMN
CABIN TYPE integer USING CABIN::integer;

ALTER TABLE episodes ALTER COLUMN
CACTUS TYPE integer USING CACTUS::integer;

ALTER TABLE episodes ALTER COLUMN
CIRCLE_FRAME TYPE integer USING CIRCLE_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
CIRRUS TYPE integer USING CIRRUS::integer;

ALTER TABLE episodes ALTER COLUMN
CLIFF TYPE integer USING CLIFF::integer;

ALTER TABLE episodes ALTER COLUMN
CLOUDS TYPE integer USING CLOUDS::integer;

ALTER TABLE episodes ALTER COLUMN
CONIFER TYPE integer USING CONIFER::integer;

ALTER TABLE episodes ALTER COLUMN
CUMULUS TYPE integer USING CUMULUS::integer;

ALTER TABLE episodes ALTER COLUMN
DECIDUOUS TYPE integer USING DECIDUOUS::integer;

ALTER TABLE episodes ALTER COLUMN
DIANE_ANDRE TYPE integer USING DIANE_ANDRE::integer;

ALTER TABLE episodes ALTER COLUMN
DOCK TYPE integer USING DOCK::integer;

ALTER TABLE episodes ALTER COLUMN
DOUBLE_OVAL_FRAME TYPE integer USING DOUBLE_OVAL_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
FARM TYPE integer USING FARM::integer;

ALTER TABLE episodes ALTER COLUMN
FENCE TYPE integer USING FENCE::integer;

ALTER TABLE episodes ALTER COLUMN
FIRE TYPE integer USING FIRE::integer;

ALTER TABLE episodes ALTER COLUMN
FLORIDA_FRAME TYPE integer USING FLORIDA_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
FLOWERS TYPE integer USING FLOWERS::integer;

ALTER TABLE episodes ALTER COLUMN
FOG TYPE integer USING FOG::integer;

ALTER TABLE episodes ALTER COLUMN
FRAMED TYPE integer USING FRAMED::integer;

ALTER TABLE episodes ALTER COLUMN
GRASS TYPE integer USING GRASS::integer;

ALTER TABLE episodes ALTER COLUMN
GUEST TYPE integer USING GUEST::integer;

ALTER TABLE episodes ALTER COLUMN
HALF_CIRCLE_FRAME TYPE integer USING HALF_CIRCLE_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
HALF_OVAL_FRAME TYPE integer USING HALF_OVAL_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
HILLS TYPE integer USING HILLS::integer;

ALTER TABLE episodes ALTER COLUMN
LAKE TYPE integer USING LAKE::integer;

ALTER TABLE episodes ALTER COLUMN
LAKES TYPE integer USING LAKES::integer;

ALTER TABLE episodes ALTER COLUMN
LIGHTHOUSE TYPE integer USING LIGHTHOUSE::integer;

ALTER TABLE episodes ALTER COLUMN
MILL TYPE integer USING MILL::integer;

ALTER TABLE episodes ALTER COLUMN
MOON TYPE integer USING MOON::integer;

ALTER TABLE episodes ALTER COLUMN
MOUNTAIN TYPE integer USING MOUNTAIN::integer;

ALTER TABLE episodes ALTER COLUMN
MOUNTAINS TYPE integer USING MOUNTAINS::integer;

ALTER TABLE episodes ALTER COLUMN
NIGHT TYPE integer USING NIGHT::integer;

ALTER TABLE episodes ALTER COLUMN
OCEAN TYPE integer USING OCEAN::integer;

ALTER TABLE episodes ALTER COLUMN
OVAL_FRAME TYPE integer USING OVAL_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
PALM_TREES TYPE integer USING PALM_TREES::integer;

ALTER TABLE episodes ALTER COLUMN
PATH TYPE integer USING PATH::integer;

ALTER TABLE episodes ALTER COLUMN
PERSON TYPE integer USING PERSON::integer;

ALTER TABLE episodes ALTER COLUMN
PORTRAIT TYPE integer USING PORTRAIT::integer;

ALTER TABLE episodes ALTER COLUMN
RECTANGLE_3D_FRAME TYPE integer USING RECTANGLE_3D_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
RECTANGULAR_FRAME TYPE integer USING RECTANGULAR_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
RIVER TYPE integer USING RIVER::integer;

ALTER TABLE episodes ALTER COLUMN
ROCKS TYPE integer USING ROCKS::integer;

ALTER TABLE episodes ALTER COLUMN
SEASHELL_FRAME TYPE integer USING SEASHELL_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
SNOW TYPE integer USING SNOW::integer;

ALTER TABLE episodes ALTER COLUMN
SNOWY_MOUNTAIN TYPE integer USING SNOWY_MOUNTAIN::integer;

ALTER TABLE episodes ALTER COLUMN
SPLIT_FRAME TYPE integer USING SPLIT_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
STEVE_ROSS TYPE integer USING STEVE_ROSS::integer;

ALTER TABLE episodes ALTER COLUMN
STRUCTURE TYPE integer USING STRUCTURE::integer;

ALTER TABLE episodes ALTER COLUMN
SUN TYPE integer USING SUN::integer;

ALTER TABLE episodes ALTER COLUMN
TOMB_FRAME TYPE integer USING TOMB_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
TREE TYPE integer USING TREE::integer;

ALTER TABLE episodes ALTER COLUMN
TREES TYPE integer USING TREES::integer;

ALTER TABLE episodes ALTER COLUMN
TRIPLE_FRAME TYPE integer USING TRIPLE_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
WATERFALL TYPE integer USING WATERFALL::integer;

ALTER TABLE episodes ALTER COLUMN
WAVES TYPE integer USING WAVES::integer;

ALTER TABLE episodes ALTER COLUMN
WINDMILL TYPE integer USING WINDMILL::integer;

ALTER TABLE episodes ALTER COLUMN
WINDOW_FRAME TYPE integer USING WINDOW_FRAME::integer;

ALTER TABLE episodes ALTER COLUMN
WINTER TYPE integer USING WINTER::integer;

ALTER TABLE episodes ALTER COLUMN
WOOD_FRAMED TYPE integer USING WOOD_FRAMED::integer;



-- CREATE A SECOND TABLE
CREATE TABLE seasons (
	season VARCHAR,
	year VARCHAR
)

-- INSERT DATA INTO NEW TABLE
INSERT INTO seasons (season, year) VALUES
('S01', '1983'),
('S02', '1983'),
('S03', '1984'),
('S04', '1984'),
('S05', '1985'),
('S06', '1985'),
('S07', '1985'),
('S08', '1986'),
('S09', '1986'),
('S10', '1986'),
('S11', '1986 - 1987'),
('S12', '1987'),
('S13', '1987'),
('S14', '1987 - 1988'),
('S15', '1988'),
('S16', '1988'),
('S17', '1989'),
('S18', '1989'),
('S19', '1990'),
('S20', '1990'),
('S21', '1990'),
('S22', '1991'),
('S23', '1991'),
('S24', '1992'),
('S25', '1992'),
('S26', '1992 - 1993'),
('S27', '1993'),
('S28', '1993'),
('S29', '1993'),
('S30', '1993 - 1994'),
('S31', '1994')

-- DROP TABLE REQUIREMENT
DROP TABLE IF EXISTS seasons

-- SET OPERATORS REQUIREMENT
SELECT season FROM seasons
UNION ALL
SELECT title FROM episodes

-- SUBQUERIES REQUIREMENT
UPDATE episodes SET trees = (SELECT SUM(bushes) FROM episodes)
WHERE title = 'A WALK IN THE WOODS'

-- ORDER OF OPERATION OF QUERIES REQUIREMENT
SELECT title, episode, cabin FROM episodes
WHERE cabin > 0 GROUP BY(title, episode, cabin)
HAVING title LIKE '%DAY%'
ORDER BY(title) ASC

-- ASSOCIATIONS REQUIREMENT / JOIN REQUIREMENT
SELECT seasons.season, seasons.year, episodes.title FROM episodes
LEFT JOIN seasons ON POSITION(seasons.season IN episodes.episode) > 0